### ISSUE TITLE
Change scrollbar width

### ISSUE THREAD

**Issue by renatomefidf** [ozonos/ozon-gtk-theme#12]
Hello,

The time is beautiful, I believe it can be better if we could use the original adaiwate color for the scrollbar, is it possible?

Sometimes the purple gets more attention than the current site or page!

Thank you!

**Comment by satya164** [comment]
Ozon Scrollbars are grey, not purple. Are you talking about GTK2 ones? Prolly you need to install the murrine engine

**Comment by renatomefidf** [comment]
I'm talking about GTK3 theme. You're right, after installing murrine the color is now correct.

There is one problem, I'm at Gnome 3.16 and the scroll bar have too much width at Ozon theme, the native is pretty thin, and with high width there is an overflow in the contents.
