### ISSUE TITLE
Dashed lines appear across user interface

### ISSUE THREAD

**Issue by tompollok** [ozonos/ozon-gtk-theme#6]
Hey guys,

first of all id like to thank you for your really great work :)

I installed the theme on my Ubuntu Gnome 14.10. The only problem i have right now is that i see lots of dashed and dotted lines across the user interface. Id be very happy if you could help me with that.

Thanks a lot again for your great work :+1: 

![bildschirmfoto 2015-03-19 um 01 06 09](https://cloud.githubusercontent.com/assets/4457821/6722098/05dbb3f0-cdd5-11e4-8eca-5d412043480e.png)

**Comment by UriHerrera** [comment]
A wild guess is that you don't have SASS, so, did you installed SASS in Ubuntu?. Also the theme is for GTK 3.14+ are you running 3.14?. @satya164

**Comment by tompollok** [comment]
Thanks for your quick reply. I have had sass installed on my machine, but the GTK version im running is 3.12. Is it a lot of hassle to upgrade it to 3.14? Unfortunately im not experienced with GTK at all.

**Comment by satya164** [comment]
You can try removing the following lines from `widgets/base.scss` if you want to use with 3.12. But it hasn't been tested, so no guarantee.

```
	outline-color: alpha($selected_bg_color, 0.5);
	outline-style: dashed;
	outline-width: 1px;
	outline-offset: -1px;
	outline-radius: $roundness;
```

**Comment by alessiodionisi** [comment]
Thanks this fix work for 3.12!

**Comment by artingei** [comment]
Fix works for me, too. Installed on Ubuntu Gnome 14.10.

**Comment by michaeljhopkins** [comment]
me as well. Ubuntu 14.10, Gnome 3.16
